import { useMemo } from 'react';
import type { UIStateBag } from '../contexts/ModalContext';

type UseUIStateForProviderParams = UIStateBag;

export const useUIStateForProvider = ({
  setIsAboutOpen,
  setIsSettingsOpen,
  setApiErrorModal,
  setIsImportModalOpen,
  setIsExportModalOpen,
  setIsSectionDropdownOpen,
  setIsSimilarityModalOpen,
  setIsSaveToLibraryModalOpen,
  setIsVersionsModalOpen,
  setIsResetModalOpen,
  setIsKeyboardShortcutsModalOpen,
  setConfirmModal,
  setPromptModal,
  setIsPasteModalOpen,
  setIsAnalysisModalOpen,
  setIsMarkupMode,
  isAboutOpen,
  isSettingsOpen,
  apiErrorModal,
  isImportModalOpen,
  isExportModalOpen,
  isSectionDropdownOpen,
  isSimilarityModalOpen,
  isSaveToLibraryModalOpen,
  isVersionsModalOpen,
  isResetModalOpen,
  isKeyboardShortcutsModalOpen,
  confirmModal,
  promptModal,
  isPasteModalOpen,
  isAnalysisModalOpen,
  activeTab,
  setActiveTab,
  isStructureOpen,
  setIsStructureOpen,
  isLeftPanelOpen,
  setIsLeftPanelOpen,
  isMarkupMode,
  markupText,
  setMarkupText,
  markupTextareaRef,
  importInputRef,
  shouldAutoGenerateTitle,
  setShouldAutoGenerateTitle,
}: UseUIStateForProviderParams): UIStateBag => {
  // Modal-related state (15 modals with their state and setters)
  const modalState = useMemo(() => ({
    setIsAboutOpen,
    setIsSettingsOpen,
    setApiErrorModal,
    setIsImportModalOpen,
    setIsExportModalOpen,
    setIsSectionDropdownOpen,
    setIsSimilarityModalOpen,
    setIsSaveToLibraryModalOpen,
    setIsVersionsModalOpen,
    setIsResetModalOpen,
    setIsKeyboardShortcutsModalOpen,
    setConfirmModal,
    setPromptModal,
    setIsPasteModalOpen,
    setIsAnalysisModalOpen,
    isAboutOpen,
    isSettingsOpen,
    apiErrorModal,
    isImportModalOpen,
    isExportModalOpen,
    isSectionDropdownOpen,
    isSimilarityModalOpen,
    isSaveToLibraryModalOpen,
    isVersionsModalOpen,
    isResetModalOpen,
    isKeyboardShortcutsModalOpen,
    confirmModal,
    promptModal,
    isPasteModalOpen,
    isAnalysisModalOpen,
  }), [
    setIsAboutOpen,
    setIsSettingsOpen,
    setApiErrorModal,
    setIsImportModalOpen,
    setIsExportModalOpen,
    setIsSectionDropdownOpen,
    setIsSimilarityModalOpen,
    setIsSaveToLibraryModalOpen,
    setIsVersionsModalOpen,
    setIsResetModalOpen,
    setIsKeyboardShortcutsModalOpen,
    setConfirmModal,
    setPromptModal,
    setIsPasteModalOpen,
    setIsAnalysisModalOpen,
    isAboutOpen,
    isSettingsOpen,
    apiErrorModal,
    isImportModalOpen,
    isExportModalOpen,
    isSectionDropdownOpen,
    isSimilarityModalOpen,
    isSaveToLibraryModalOpen,
    isVersionsModalOpen,
    isResetModalOpen,
    isKeyboardShortcutsModalOpen,
    confirmModal,
    promptModal,
    isPasteModalOpen,
    isAnalysisModalOpen,
  ]);

  // Panel and layout state (tabs, panels, markup mode)
  const layoutState = useMemo(() => ({
    activeTab,
    setActiveTab,
    isStructureOpen,
    setIsStructureOpen,
    isLeftPanelOpen,
    setIsLeftPanelOpen,
    isMarkupMode,
    setIsMarkupMode,
  }), [
    activeTab,
    setActiveTab,
    isStructureOpen,
    setIsStructureOpen,
    isLeftPanelOpen,
    setIsLeftPanelOpen,
    isMarkupMode,
    setIsMarkupMode,
  ]);

  // Text and content state
  const textState = useMemo(() => ({
    markupText,
    setMarkupText,
    shouldAutoGenerateTitle,
    setShouldAutoGenerateTitle,
  }), [
    markupText,
    setMarkupText,
    shouldAutoGenerateTitle,
    setShouldAutoGenerateTitle,
  ]);

  // DOM references (stable, but included for completeness)
  const refs = useMemo(() => ({
    markupTextareaRef,
    importInputRef,
  }), [
    markupTextareaRef,
    importInputRef,
  ]);

  // Compose the final context value from semantic sub-groups
  return useMemo(() => ({
    ...modalState,
    ...layoutState,
    ...textState,
    ...refs,
  }), [
    modalState,
    layoutState,
    textState,
    refs,
  ]);
};
